#!/bin/bash
mvn clean install
scp -i ~/development/pauwelsarch.pem target/peers-1.0-SNAPSHOT-jar-with-dependencies.jar ubuntu@ec2-18-221-5-112.us-east-2.compute.amazonaws.com:~/
scp -i ~/development/pauwelsarch.pem target/peers-1.0-SNAPSHOT-jar-with-dependencies.jar ubuntu@ec2-18-220-90-71.us-east-2.compute.amazonaws.com:~/

